# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose -f docker-compose.sqlite.yaml build
#      Start app: docker-compose -f docker-compose.sqlite.yaml up -d app
#       Stop all: docker-compose -f docker-compose.sqlite.yaml down
#
version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  SITE_FRONTEND_URL: "http://localhost:8080"
  SITE_API_URL: "http://localhost:8080"
  NO_REPLY_EMAIL_HOSTNAME: smtp.mailtrap.io
  NO_REPLY_EMAIL: aaaaaaaaaaaaaaa
  NO_REPLY_EMAIL_USERNAME: aaaaaaaaaaaaaaa
  NO_REPLY_EMAIL_PASSWORD: aaaaaaaaaaaaaaa

services:
  app:
    image: tangpoetry:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
